imflip		:	imflip.c ImageStuff.c ImageStuff.h
				gcc imflip.c ImageStuff.c -o imflip

imflipP		:	imflipP.c ImageStuff.c ImageStuff.h
				gcc imflipP.c ImageStuff.c -o imflipP -lpthread

imflipPM	:	imflipPM.c ImageStuff.c ImageStuff.h
				gcc imflipPM.c ImageStuff.c -o imflipPM -lpthread

imrotate	:	imrotate.c ImageStuff.c ImageStuff.h
				gcc imrotate.c ImageStuff.c -o imrotate -lpthread -lm

imrotateMC	:	imrotateMC.c ImageStuff.c ImageStuff.h
				gcc imrotateMC.c ImageStuff.c -o imrotateMC -lpthread -lm
				
				