imflip		:	imflip.c ImageStuff.c ImageStuff.h
				gcc imflip.c ImageStuff.c -o imflip

imflipP		:	imflipP.c ImageStuff.c ImageStuff.h
				gcc imflipP.c ImageStuff.c -o imflipP -lpthread

imflipPM	:	imflipPM.c ImageStuff.c ImageStuff.h
				gcc imflipPM.c ImageStuff.c -o imflipPM -lpthread

imrotate	:	imrotate.c ImageStuff.c ImageStuff.h
				gcc imrotate.c ImageStuff.c -o imrotate -lpthread -lm

imrotateMC	:	imrotateMC.c ImageStuff.c ImageStuff.h
				gcc imrotateMC.c ImageStuff.c -o imrotateMC -lpthread -lm

imedge		:	imedge.c ImageStuff.c ImageStuff.h
				gcc imedge.c ImageStuff.c -o imedge -lpthread -lm
				
imedgeMC	:	imedgeMC.c ImageStuff.c ImageStuff.h
				gcc imedgeMC.c ImageStuff.c -o imedgeMC -lpthread -lm
				
imedgeMCT	:	imedgeMCT.c ImageStuff.c ImageStuff.h
				gcc imedgeMCT.c ImageStuff.c -o imedgeMCT -lpthread -lm

imedgeDEBUG	:	imedgeDEBUG.c ImageStuff.c ImageStuff.h
				gcc imedgeDEBUG.c ImageStuff.c -o imedgeDEBUG -lpthread -lm
