imflip		:	imflip.c ImageStuff.c ImageStuff.h
				gcc imflip.c ImageStuff.c -o imflip

imflipP		:	imflipP.c ImageStuff.c ImageStuff.h
				gcc imflipP.c ImageStuff.c -o imflipP -lpthread


imflipPM	:	imflipPM.c ImageStuff.c ImageStuff.h
				gcc imflipPM.c ImageStuff.c -o imflipPM -lpthread

				
				